[lint]
select = ["E", "F", "I", "B", "Q"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["darwix_ai", "transcriptions", "suggestions", "common"]
combine-as-imports = true
force-sort-within-sections = true

[format]
quote-style = "double"